# -*- coding: utf-8 -*-
"""JoaoPedroPaciello - trabalho3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vABH9qvGMMO9R7EJgXX51K_MW6hh2nG2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_votos = pd.read_csv('votos_por_secao.csv', sep=';')
df_locais = pd.read_csv('locais_de_votacao.csv', sep=';')

print(df_votos)
print(df_locais)

#QUESTAO1
df_merged = pd.merge(df_votos, df_locais, on='secao', how='inner')
print(df_merged)

votos_por_local = df_merged.groupby('local')['votos'].sum()
print(f'locais com mais votos: {votos_por_local}')

print('--------')

local_votado = votos_por_local.idxmax()
print(f'local mais votado: {local_votado}')

#QUESTAO2
df_locais.merge(df_votos, on='secao', how='left')

votos_por_local_candidato = df_merged.groupby(['local', 'candidato'])['votos'].sum().reset_index()

max_votos = votos_por_local_candidato.groupby('local')['votos'].idxmax()

vencedores_por_local = votos_por_local_candidato.loc[max_votos]

print(vencedores_por_local[['local', 'candidato', 'votos']].reset_index(drop=True))

df_pivot = votos_por_local_candidato.pivot(index='local', columns='candidato', values='votos').fillna(0)

print('--------')

plt.figure(figsize=(12, 7))
df_pivot.plot(kind='bar', stacked=True, ax=plt.gca(), colormap='viridis')

plt.title('Total de Votos por Candidato em Cada Local de Votação', fontsize=14)
plt.xlabel('Local de Votação', fontsize=12)
plt.ylabel('Total de Votos', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Candidato', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

#QUESTAO3
df_outer_merged = pd.merge(df_locais, df_votos, on='secao', how='outer')
print(df_outer_merged)

secoes_sem_votos = df_outer_merged[df_outer_merged['candidato'].isnull()].copy()

secoes_sem_votos = secoes_sem_votos[['secao', 'local', 'endereco']]

secoes_sem_votos.drop_duplicates(subset=['secao'], inplace=True)

print("\nSeções com Local de Votação, mas sem Registro de Votos")
if not secoes_sem_votos.empty:
    print("Essas seções existem na lista de locais, mas não estão no arquivo de votos:")
    print(secoes_sem_votos.to_markdown(index=False))
else:
    print("Nenhuma inconsistência encontrada: todas as seções de votação têm pelo menos um registro de voto.")

#QUESTAO4
distribuicao_estatistica = df_votos.groupby('candidato')['votos'].describe()

plt.figure(figsize=(10, 6))
sns.boxplot(x='candidato', y='votos', data=df_votos, palette='Set2')
plt.title('Distribuição de Votos por Candidato em Todas as Seções', fontsize=16)
plt.xlabel('Candidato', fontsize=12)
plt.ylabel('Número de Votos por Seção', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

#QUESTAO5
votos_totais_por_candidato = df_votos.groupby('candidato')['votos'].sum()
print(votos_totais_por_candidato)

plt.figure(figsize=(8, 6))
votos_totais_por_candidato.plot(kind='bar', color=['skyblue', 'salmon', 'lightgreen'])
plt.title('Total de Votos por Candidato', fontsize=16)
plt.xlabel('Candidato', fontsize=12)
plt.ylabel('Total de Votos', fontsize=12)
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='-', alpha=0.7)
plt.tight_layout()
plt.show()